# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('key', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Group')),
            ],
        ),
    ]
