# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOMe',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('issuing_date', models.DateField(auto_now_add=True, verbose_name='date issued')),
                ('issuer_signature', models.CharField(blank=True, default='', max_length=400)),
                ('borrower_signature', models.CharField(blank=True, default='', max_length=400)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uome_borrower', to='rest_app.User')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Group')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uome_lender', to='rest_app.User')),
            ],
            options={
                'verbose_name_plural': "UOMe's",
            },
        ),
    ]
