# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_uome'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_borrower', to='rest_app.User')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Group')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_lender', to='rest_app.User')),
            ],
        ),
    ]
